document.addEventListener("DOMContentLoaded",()=>{
const id=new URLSearchParams(location.search).get("course")||"python";const c=courses.find(x=>x.id===id)||courses[0];
document.title=`${c.title} | Software Academy`;
const app=document.getElementById("detailsApp");
app.innerHTML=`<section class="detail-hero"><div class="container"><div class="row align-items-center g-5">
<div class="col-lg-7"><span class="eyebrow">${c.category.toUpperCase()}</span><h1>${c.title}</h1><p class="detail-lead">${c.desc}</p><div class="detail-rating"><span class="rating">★★★★★</span><b>${c.rating}</b><span>(${c.students} students)</span></div><div class="detail-instructor"><div class="mini-avatar">${c.instructor.split(" ").map(x=>x[0]).join("")}</div><div><small>Instructor</small><b>${c.instructor}</b></div></div></div>
<div class="col-lg-5"><div class="detail-image"><img src="${c.image}" alt="${c.title}"></div></div></div></div></section>
<section class="detail-content section-padding"><div class="container"><div class="row g-5"><div class="col-lg-8">
<div class="detail-panel"><span class="eyebrow">WHAT YOU'LL LEARN</span><h2>Build skills that <span class="gradient-text">work.</span></h2><div class="outcome-grid">${c.outcomes.map(x=>`<div><i class="fa-solid fa-circle-check"></i>${x}</div>`).join("")}</div></div>
<div class="detail-panel mt-4"><span class="eyebrow">CURRICULUM</span><h2>Course <span class="gradient-text">roadmap</span></h2><div class="accordion custom-accordion" id="curriculum">${c.curriculum.map((m,i)=>`<div class="accordion-item"><h2 class="accordion-header"><button class="accordion-button ${i?'collapsed':''}" data-bs-toggle="collapse" data-bs-target="#m${i}"><span>Module ${m[0]}</span>${m[1]}</button></h2><div id="m${i}" class="accordion-collapse collapse ${i===0?'show':''}" data-bs-parent="#curriculum"><div class="accordion-body">${m[2]}</div></div></div>`).join("")}</div></div>
<div class="detail-panel mt-4"><span class="eyebrow">PRACTICAL LEARNING</span><h2>Portfolio-ready <span class="gradient-text">projects.</span></h2><p>Throughout the course you will apply concepts to practical exercises and project work designed to strengthen your portfolio and problem-solving ability.</p><div class="project-pills"><span><i class="fa-solid fa-diagram-project"></i>${c.projects} Projects</span><span><i class="fa-solid fa-video"></i>${c.lessons} Lessons</span><span><i class="fa-solid fa-award"></i>Certificate</span></div></div>
</div><div class="col-lg-4"><aside class="enroll-card sticky-lg-top"><img src="${c.image}" alt="" loading="lazy"><div class="price"><del>${c.oldFee}</del><strong>${c.fee}</strong></div><button onclick="alert('Enrollment form opened. Connect this button to your backend/payment system.')" class="btn btn-primary-custom btn-lg rounded-pill w-100">Enroll Now <i class="fa-solid fa-arrow-right ms-2"></i></button><hr><h4>This course includes</h4><ul><li><i class="fa-regular fa-clock"></i>${c.duration} access</li><li><i class="fa-solid fa-signal"></i>${c.level}</li><li><i class="fa-solid fa-language"></i>English / Urdu</li><li><i class="fa-solid fa-award"></i>Certificate of completion</li><li><i class="fa-solid fa-laptop"></i>Practical projects</li></ul></aside></div></div></div></section>
<footer class="footer"><div class="container"><div class="footer-bottom"><span>© 2026 Software Academy</span><a href="index.html#courses">Browse all courses</a></div></div></footer>`;
});